name: flutter_sample_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: 3.3.1
  flutter: 3.19.3

dependencies:
  core_model:
    path: ../../packages/core/model
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.6
  go_router: 13.2.0
  hooks_riverpod: 2.5.1
  riverpod_annotation: 2.3.5
  firebase_core: 2.30.0

dev_dependencies:
  build_runner: 2.4.8
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.0
  go_router_builder: 2.4.1
  riverpod_generator: 2.4.0

flutter:
  uses-material-design: true