name: core_common
description: This package provides convenience functions and other functions commonly used in packages.
version: 1.0.0
publish_to: "none"

## 便宜的にFlutterPackageとしていますが、DartPackageとして扱ってください。
environment:
  sdk: 3.3.1
  flutter: 3.19.3

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: 2.4.1

dev_dependencies:
  build_runner: 2.4.8
  flutter_test:
    sdk: flutter
  freezed: 2.5.2

flutter:
