name: core_network
description: This package provides network operations.
version: 1.0.0
publish_to: "none"

## 便宜的にFlutterPackageとしていますが、DartPackageとして扱ってください。
environment:
  sdk: 3.3.1
  flutter: 3.19.3

dependencies:
  cloud_firestore: 4.17.0
  collection: 1.18.0
  core_common:
    path: ../common
  core_model:
    path: ../model
  flutter:
    sdk: flutter
  freezed_annotation: 2.4.1
  json_annotation: 4.8.1
  riverpod_annotation: 2.3.5

dev_dependencies:
  build_runner: 2.4.8
  flutter_test:
    sdk: flutter
  freezed: 2.5.2
  json_serializable: 6.7.1
  riverpod_generator: 2.4.0

flutter:
